name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - origen-frontend-webapp
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - origen-frontend-webapp

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # Set up Node.js 16 for the build steps
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      # Install dependencies using Node.js 16
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend  # Adjust if frontend is in a different directory

      # Build the project using Node.js 16
      - name: Build the Project
        run: npm run build
        working-directory: ./frontend  # Adjust if frontend is in a different directory

      # Deploy to Azure Static Web Apps using the pre-built files in ./frontend/build
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUD_018C2961E }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "" # Set to empty because we're using pre-built files
          api_location: "" # Api source code path - optional
          output_location: "./frontend/build" # Built app content directory
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
